const XLSX = require('xlsx');
const path = require('path');

const data = [
    {
        FullName: "Arjun K. Patel",
        FathersName: "Kantilal Patel",
        Email: "arjun.patel@example.com",
        Mobile: "9825012345",
        Gender: "Male",
        DOB: "1995-05-10",
        Password: "Password@123",
        PermanentAddress: "101, Shanti Sadan, Near Income Tax office, Ahmedabad, Gujarat 380009",
        State: "Gujarat",
        "10thBoard": "GSEB",
        "10thPassingYear": 2011,
        "10thPercentage": 82.5,
        "12thBoard": "GSEB",
        "12thPassingYear": 2013,
        "12thPercentage": 85.0,
        GraduationDegree: "B.E.",
        GradSpecialization: "Civil Engineering",
        GradYear: 2017,
        GradPercentage: 78.4,
        GradCGPA: 8.2,
        QualifyingDegree: "M.E.",
        QualifyingSpecialization: "Structural Engineering",
        QualifyingPercentage: 80.0
    },
    {
        FullName: "Dhruvi M. Shah",
        FathersName: "Maheshkumar Shah",
        Email: "dhruvi.shah@example.com",
        Mobile: "9426012345",
        Gender: "Female",
        DOB: "1998-08-22",
        Password: "SecurePass@2024",
        PermanentAddress: "A-402, Royal Residency, Alkapuri, Vadodara, Gujarat 390007",
        State: "Gujarat",
        "10thBoard": "CBSE",
        "10thPassingYear": 2014,
        "10thPercentage": 91.2,
        "12thBoard": "CBSE",
        "12thPassingYear": 2016,
        "12thPercentage": 89.5,
        GraduationDegree: "B.Com",
        GradSpecialization: "Accountancy",
        GradYear: 2019,
        GradPercentage: 84.6,
        GradCGPA: 8.8
    },
    {
        FullName: "Karan B. Jadeja",
        FathersName: "Bhupendrasinh Jadeja",
        Email: "karan.jadeja@example.com",
        Mobile: "9724012345",
        Gender: "Male",
        DOB: "1996-12-05",
        Password: "Karan@Strong99",
        PermanentAddress: "Jadeja Niwas, Raiya Road, Rajkot, Gujarat 360001",
        State: "Gujarat",
        "10thBoard": "GSEB",
        "10thPassingYear": 2012,
        "10thPercentage": 75.8,
        "12thBoard": "GSEB",
        "12thPassingYear": 2014,
        "12thPercentage": 78.2,
        GraduationDegree: "B.Sc.",
        GradSpecialization: "Information Technology",
        GradYear: 2017,
        GradPercentage: 72.5,
        GradCGPA: 7.5,
        QualifyingDegree: "M.Sc. IT",
        QualifyingSpecialization: "Data Science",
        QualifyingPercentage: 76.8
    },
    {
        FullName: "Anjali R. Mehta",
        FathersName: "Rajeshbhai Mehta",
        Email: "anjali.mehta@example.com",
        Mobile: "9978012345",
        Gender: "Female",
        DOB: "1999-03-15",
        Password: "MehtaAnjali#1",
        PermanentAddress: "12, Girdhar Nagar Society, Adajan, Surat, Gujarat 395009",
        State: "Gujarat",
        "10thBoard": "GSEB",
        "10thPassingYear": 2015,
        "10thPercentage": 88.4,
        "12thBoard": "GSEB",
        "12thPassingYear": 2017,
        "12thPercentage": 86.2,
        GraduationDegree: "B.B.A.",
        GradSpecialization: "Human Resources",
        GradYear: 2020,
        GradPercentage: 81.0,
        GradCGPA: 8.1
    },
    {
        FullName: "Rushil S. Desai",
        FathersName: "Sureshbhai Desai",
        Email: "rushil.desai@example.com",
        Mobile: "9898012345",
        Gender: "Male",
        DOB: "1997-07-28",
        Password: "DesaiRushil$7",
        PermanentAddress: "Plot No. 45, Sector 5, Gandhinagar, Gujarat 382005",
        State: "Gujarat",
        "10thBoard": "ICSE",
        "10thPassingYear": 2013,
        "10thPercentage": 84.5,
        "12thBoard": "ISC",
        "12thPassingYear": 2015,
        "12thPercentage": 82.8,
        GraduationDegree: "B.Tech",
        GradSpecialization: "Mechanical Engineering",
        GradYear: 2019,
        GradPercentage: 77.5,
        GradCGPA: 8.0
    },
    {
        FullName: "Priya V. Chudasama",
        FathersName: "Vijaybhai Chudasama",
        Email: "priya.chudasama@example.com",
        Mobile: "9428012345",
        Gender: "Female",
        DOB: "2000-11-12",
        Password: "PriyaV#Chuda20",
        PermanentAddress: "Aamba Wadi, Near Bus Station, Junagadh, Gujarat 362001",
        State: "Gujarat",
        "10thBoard": "GSEB",
        "10thPassingYear": 2016,
        "10thPercentage": 79.4,
        "12thBoard": "GSEB",
        "12thPassingYear": 2018,
        "12thPercentage": 80.6,
        GraduationDegree: "B.A.",
        GradSpecialization: "Economics",
        GradYear: 2021,
        GradPercentage: 74.2,
        GradCGPA: 7.4
    },
    {
        FullName: "Hardik A. Parmar",
        FathersName: "Ashokbhai Parmar",
        Email: "hardik.parmar@example.com",
        Mobile: "9725012345",
        Gender: "Male",
        DOB: "1994-01-20",
        Password: "HardikP@Parmar1",
        PermanentAddress: "Nr. Kalupur Bridge, Relief Road, Ahmedabad, Gujarat 380001",
        State: "Gujarat",
        "10thBoard": "GSEB",
        "10thPassingYear": 2010,
        "10thPercentage": 72.5,
        "12thBoard": "GSEB",
        "12thPassingYear": 2012,
        "12thPercentage": 74.0,
        GraduationDegree: "B.C.A.",
        GradSpecialization: "Computer Applications",
        GradYear: 2015,
        GradPercentage: 68.8,
        GradCGPA: 6.9
    },
    {
        FullName: "Sonal K. Solanki",
        FathersName: "Kamleshbhai Solanki",
        Email: "sonal.solanki@example.com",
        Mobile: "9824054321",
        Gender: "Female",
        DOB: "1996-06-30",
        Password: "SonalSolanki@22",
        PermanentAddress: "Vithal Park, Main Road, Jamnagar, Gujarat 361001",
        State: "Gujarat",
        "10thBoard": "CBSE",
        "10thPassingYear": 2012,
        "10thPercentage": 86.0,
        "12thBoard": "CBSE",
        "12thPassingYear": 2014,
        "12thPercentage": 84.5,
        GraduationDegree: "B.Pharm",
        GradSpecialization: "Pharmacy",
        GradYear: 2018,
        GradPercentage: 79.8,
        GradCGPA: 8.3
    },
    {
        FullName: "Rohan J. Vaghela",
        FathersName: "Jayeshbhai Vaghela",
        Email: "rohan.vaghela@example.com",
        Mobile: "9157012345",
        Gender: "Male",
        DOB: "2001-02-14",
        Password: "RohanV#Vaghela!",
        PermanentAddress: "Station Road, Near Tower, Mehsana, Gujarat 384001",
        State: "Gujarat",
        "10thBoard": "GSEB",
        "10thPassingYear": 2017,
        "10thPercentage": 74.2,
        "12thBoard": "GSEB",
        "12thPassingYear": 2019,
        "12thPercentage": 76.5,
        GraduationDegree: "B.E.",
        GradSpecialization: "Electrical Engineering",
        GradYear: 2023,
        GradPercentage: 71.0,
        GradCGPA: 7.2
    },
    {
        FullName: "Sneha L. Trivedi",
        FathersName: "Lalitbhai Trivedi",
        Email: "sneha.trivedi@example.com",
        Mobile: "9408012345",
        Gender: "Female",
        DOB: "1997-09-05",
        Password: "SnehaT#Trivedi9",
        PermanentAddress: "Brahminkund, Near Palace, Bhavnagar, Gujarat 364001",
        State: "Gujarat",
        "10thBoard": "GSEB",
        "10thPassingYear": 2013,
        "10thPercentage": 90.5,
        "12thBoard": "GSEB",
        "12thPassingYear": 2015,
        "12thPercentage": 88.0,
        GraduationDegree: "B.B.A.",
        GradSpecialization: "Finance",
        GradYear: 2018,
        GradPercentage: 83.2,
        GradCGPA: 8.5
    }
];

const ws = XLSX.utils.json_to_sheet(data);
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Users");

const outputPath = path.join(__dirname, 'sample_users.xlsx');
XLSX.writeFile(wb, outputPath);
console.log(`✅ Realistic sample Excel with 10 candidates created at: ${outputPath}`);
